---
deployment:
  tasks:
    # Set production environment
    - export NODE_ENV=production

    # Navigate to the cloned repository
    - cd $HOME/repositories/mala-web

    # Install npm dependencies
    - npm install

    # Build the React (Vite) app
    - npm run build

    # Clear the public_html folder but keep .htaccess if it exists
    - find $HOME/public_html -mindepth 1 ! -name ".htaccess" -exec rm -rf {} +

    # Copy the new build to public_html
    - cp -r dist/* $HOME/public_html/

    # Restore .htaccess from repo if you have a custom one
    - if [ -f $HOME/repositories/mala-web/.htaccess ]; then cp $HOME/repositories/mala-web/.htaccess $HOME/public_html/; fi
