---
deployment:
  tasks:
    - "set -e"
    - "cd $HOME/repositories/mala-web || exit 1"
    - 'export NVM_DIR="$HOME/.nvm" && if [ -s "$NVM_DIR/nvm.sh" ]; then . "$NVM_DIR/nvm.sh" && nvm install 20 && nvm use 20; fi'
    - "if [ -f package-lock.json ]; then npm ci --prefer-offline --no-audit --progress=false; else npm install --no-audit --progress=false; fi"
    - "export NODE_ENV=production && npm run build"
    - 'find $HOME/public_html -mindepth 1 ! -name ".htaccess" -exec rm -rf {} + || true'
    - "cp -a dist/. $HOME/public_html/"
    - "if [ -f $HOME/repositories/mala-web/.htaccess ]; then cp $HOME/repositories/mala-web/.htaccess $HOME/public_html/; fi"
