deployment:
  tasks:
    - export NODE_ENV=production
    - cd $HOME/repositories/mala-web
    - npm install
    - npm run build
    - find $HOME/public_html -mindepth 1 ! -name ".htaccess" -exec rm -rf {} +
    - cp -r dist/* $HOME/public_html/
    - if [ -f $HOME/repositories/mala-web/.htaccess ]; then cp $HOME/repositories/mala-web/.htaccess $HOME/public_html/; fi
